version: '3'

services:
    nginx:
        image: nginx:latest
        restart: unless-stopped
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "6969:80"
        depends_on:
            - app
        container_name: nginx
        networks:
            - service_network

    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: unless-stopped
        volumes:
            - ./:/var/www/
        depends_on:
            - db
            - redis
        container_name: backend_app
        networks:
            - service_network
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            PHP_IDE_CONFIG: serverName=pet_service_docker
            USER_NAME: ${USER_NAME}

    db:
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3464:5432"
        container_name: db
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        networks:
            - service_network

    redis:
        image: redis:latest
        restart: unless-stopped
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - service_network

networks:
    service_network:
